apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://argocd-dns-acfcz47p.hcp.eastus.azmk8s.io:443
  project: default
  source:
    path: .
    repoURL: https://github.com/akhil112/k8-gitops-pipelines
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
